AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: AWS SAM with TypeScript sharing package.json across lambda functions

Globals:
    Function:
        Timeout: 3

Resources:
    CreateShortUrlFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/functions
            Handler: create-url.handler
            Runtime: nodejs18.x
            Architectures:
                - x86_64
            Events:
                CreateUrl:
                    Type: Api
                    Properties:
                        Path: /create-url
                        Method: post
            Environment:
                Variables:
                    ACCESS_KEY: INSERT_ACCESS_KEY
                    SECRET_KEY: INSERT_SECRET_KEY
                    BASE_URL: localhost.com
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                Sourcemap: true
                EntryPoints:
                    - create-url.ts

    RedirectUrlFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/functions
            Handler: redirect-url.handler
            Runtime: nodejs18.x
            Architectures:
                - x86_64
            Events:
                CreateUrl:
                    Type: Api
                    Properties:
                        Path: /{id}
                        Method: get
            Environment:
                Variables:
                    ACCESS_KEY: INSERT_ACCESS_KEY
                    SECRET_KEY: INSERT_SECRET_KEY
                    BASE_URL: localhost.com
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                Sourcemap: true
                EntryPoints:
                    - redirect-url.ts

Outputs:
    HelloWorldApi:
        Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
    CreateShortUrlFunction:
        Description: 'Create Short Url Lambda Function ARN'
        Value: !GetAtt CreateShortUrlFunction.Arn
    RedirectUrlFunction:
        Description: 'Redirect Url Lambda Function ARN'
        Value: !GetAtt RedirectUrlFunction.Arn
